Repository conda-incubator/jupyterlab-conda-store, pull requests merged in 2023-09, with the labels that each got.

#19 Typo fixes in `PULL_REQUEST_TEMPLATE.md`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs: review 👀, type: maintenance 🛠

#22 Add instructions for installing the package in development version
  README.md
Labels: area: documentation 📖

#21 ENH - pre-release maintenance
  .github/workflows/build.yml
  .github/workflows/build_and_deploy_release.yml
  .github/workflows/check-release.yml
  README.md
  pyproject.toml
Labels: status: in progress 🏗, type: maintenance 🛠
